// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbP01OUllTqIPl7aDIapEvGKg_n-vdTcs',
    appId: '1:383488571093:web:b09014f7d9cd52795b145c',
    messagingSenderId: '383488571093',
    projectId: 'koskeu-digital',
    authDomain: 'koskeu-digital.firebaseapp.com',
    storageBucket: 'koskeu-digital.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyS9gXiwYNXz7Lyy2iNaJlUbwzU_skPV4',
    appId: '1:383488571093:android:6bf22acaaf16eaaf5b145c',
    messagingSenderId: '383488571093',
    projectId: 'koskeu-digital',
    storageBucket: 'koskeu-digital.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBbP01OUllTqIPl7aDIapEvGKg_n-vdTcs',
    appId: '1:383488571093:web:a4b9f29ffe58ab5e5b145c',
    messagingSenderId: '383488571093',
    projectId: 'koskeu-digital',
    authDomain: 'koskeu-digital.firebaseapp.com',
    storageBucket: 'koskeu-digital.firebasestorage.app',
  );
}
